blank_issues_enabled: false
contact_links:
  - name: Ask a Question, Discuss
    url: https://github.com/testing-library/eslint-plugin-testing-library/discussions
    about: Look for `eslint-plugin-testing-library` Questions and Discussions or start a new one
